source 'https://github.com/cocoapods/specs.git'

platform :ios, '6.0'

xcodeproj 'SSOperationsExample'

pod 'SSOperations', :path => "../"

target :SSOperationsTests, :exclusive => true do
    pod 'MXGSynchronizeTest'
end